package com.kardji.models.entity;
// Generated 27 mar. 2021 17:10:37 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cartas generated by hbm2java
 */
@Entity
@Table(name = "cartas")
public class Cartas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Lecciones lecciones;
	private String keyWord;
	private String shortStory;
	private String asComponent;
	private String kanjiChar;

	public Cartas() {
	}

	public Cartas(int id) {
		this.id = id;
	}

	public Cartas(int id, Lecciones lecciones, String keyWord, String shortStory, String asComponent, String imageUrl) {
		this.id = id;
		this.lecciones = lecciones;
		this.keyWord = keyWord;
		this.shortStory = shortStory;
		this.asComponent = asComponent;
		this.kanjiChar = imageUrl;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLeccion")
	public Lecciones getLecciones() {
		return this.lecciones;
	}

	@JsonIgnore
	public void setLecciones(Lecciones lecciones) {
		this.lecciones = lecciones;
	}

	@Column(name = "keyWord")
	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	@Column(name = "shortStory")
	public String getShortStory() {
		return this.shortStory;
	}

	public void setShortStory(String shortStory) {
		this.shortStory = shortStory;
	}

	@Column(name = "asComponent")
	public String getAsComponent() {
		return this.asComponent;
	}

	public void setAsComponent(String asComponent) {
		this.asComponent = asComponent;
	}

	@Column(name = "kanjiChar")
	public String getKanjiChar() {
		return this.kanjiChar;
	}

	public void setKanjiChar(String imageUrl) {
		this.kanjiChar = imageUrl;
	}

}
