INSERT INTO lecciones(id,name,description,image_url) VALUES(1,'Leccion1','Descripcion Default','img/imagen1.jpg');
INSERT INTO lecciones(id,name,description,image_url) VALUES(2,'Leccion2','Descripcion Default','img/imagen2.jpg');
INSERT INTO lecciones(id,name,description,image_url) VALUES(3,'Leccion3','Descripcion Default','img/imagen3.jpg');
INSERT INTO lecciones(id,name,description,image_url) VALUES(4,'Leccion4','Descripcion Default','img/imagen4.jpg');


INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(1,'Uno','Un trazo horizontal, contrariamente al numeral romano I, que se encuentra en posición vertical.','Adquiere el significado de suelo o de techo según su posición','ー',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(2,'Dos','El kanji de dos es una simple duplicación del trazo horizontal que significa uno.','','ニ',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(3,'Tres','El kanji de tres simplemente triplica un único trazo horizontal','','三',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(4,'Cuatro','Supondremos que ya conocías de antes los números del 1 al 10, por lo que aplazaremos el cuento de este carácter hasta más adelante.','Boca y Piernas','四',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(5,'Cinco','Al igual que hemos hecho en el caso de cuatro, vamos a dejar para más adelante el estudio de los componentes de este carácter.','','五',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(6,'Seis','Al igual que hemos hecho anteriormente, de momento vamos a prescindir de una explicación.','Chistera y Patas','六',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(7,'Siete','Observa que el primer trazo atraviesa limpiamente al segundo. Esta característica nos permitirá diferenciar el kanji siete del kanji que significa cuchara.','Cortar en dados','七',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(8,'Ocho','Igual que el numeral arábigo “8” está formado por un pequeño círculo sobre otro círculo ligeramente mayor, el kanji de ocho está formado por una línea corta seguida por otra línea un poco más larga, inclinada hacia la primera pero sin llegar a tocarla.','','八',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(9,'Nueve','Si haces un pequeño esfuerzo para recordar el orden de trazos de este kanji, no tendrás dificultades posteriormente para distinguirlo del kanji de fuerza.','Beisbol (Ya que hay 9 miembros','九',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(10,'Diez','Si volteas este carácter en cualquier dirección obtendrás la x que se utiliza para indicar diez en los números romanos','Diez y Aguja','十',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(11,'Boca','El kanji de boca es claramente un pictograma. En la escritura de los kanji no existe la forma circular, por lo que utilizaremos un cuadrado para indicar el círculo.','Abertura o entrada a una cueva, la boca de un arma, de un río, así como la mismísima boca que tenemos en la cara.','ロ',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(12,'Dia','Este carácter pretende ser el pictograma de un sol. Si recordamos lo que hemos comentado antes acerca de las formas redondeadas, no nos será muy difícil visualizar el círculo y la gran sonrisa que caracteriza a los dibujos más simples que hacemos del sol.','Sol, día y lengua que se agita dentro de la boca.','日',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(13,'Mes','Este carácter es en realidad un dibujo de la luna. Las dos líneas horizontales representan los ojos y la boca de la cara que solemos ver en la superficie de la luna, dibujada por los cráteres del satélite. Los ojos de la luna japonesa son tan alargados que se han unido en una sola línea, y en la línea inferior vemos la boca de esta luna con una generosa sonrisa.','Luna, carne o parte del cuerpo','月',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(14,'Campo de Arroz','Este kanji es otro pictograma con la forma de un campo de arroz dividido en cuatro parcelas y visto desde el aire.','Campo de Arroz y Cerebro','田',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(15,'Ojo','Una vez más, si redondeamos los ángulos y curvamos las líneas centrales hacia arriba y hacia abajo respectivamente, obtendremos algo parecido al dibujo de un ojo.','Ojo y Globo Ocular','目',1);