INSERT INTO lecciones(id,name,description,image_url) VALUES(1,'Leccion1','Descripcion Default','img/imagen1.jpg');
INSERT INTO lecciones(id,name,description,image_url) VALUES(2,'Leccion2','Descripcion Default','img/imagen2.jpg');
INSERT INTO lecciones(id,name,description,image_url) VALUES(3,'Leccion3','Descripcion Default','img/imagen3.jpg');
INSERT INTO lecciones(id,name,description,image_url) VALUES(4,'Leccion4','Descripcion Default','img/imagen4.jpg');

--Leccion 1
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(1,'Uno','Un trazo horizontal, contrariamente al numeral romano I, que se encuentra en posición vertical.','Adquiere el significado de suelo o de techo según su posición','ー',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(2,'Dos','El kanji de dos es una simple duplicación del trazo horizontal que significa uno.','','ニ',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(3,'Tres','El kanji de tres simplemente triplica un único trazo horizontal','','三',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(4,'Cuatro','Supondremos que ya conocías de antes los números del 1 al 10, por lo que aplazaremos el cuento de este carácter hasta más adelante.','Boca y Piernas','四',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(5,'Cinco','Al igual que hemos hecho en el caso de cuatro, vamos a dejar para más adelante el estudio de los componentes de este carácter.','','五',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(6,'Seis','Al igual que hemos hecho anteriormente, de momento vamos a prescindir de una explicación.','Chistera y Patas','六',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(7,'Siete','Observa que el primer trazo atraviesa limpiamente al segundo. Esta característica nos permitirá diferenciar el kanji siete del kanji que significa cuchara.','Cortar en dados','七',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(8,'Ocho','Igual que el numeral arábigo “8” está formado por un pequeño círculo sobre otro círculo ligeramente mayor, el kanji de ocho está formado por una línea corta seguida por otra línea un poco más larga, inclinada hacia la primera pero sin llegar a tocarla.','','八',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(9,'Nueve','Si haces un pequeño esfuerzo para recordar el orden de trazos de este kanji, no tendrás dificultades posteriormente para distinguirlo del kanji de fuerza.','Beisbol (Ya que hay 9 miembros','九',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(10,'Diez','Si volteas este carácter en cualquier dirección obtendrás la x que se utiliza para indicar diez en los números romanos','Diez y Aguja','十',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(11,'Boca','El kanji de boca es claramente un pictograma. En la escritura de los kanji no existe la forma circular, por lo que utilizaremos un cuadrado para indicar el círculo.','Abertura o entrada a una cueva, la boca de un arma, de un río, así como la mismísima boca que tenemos en la cara.','ロ',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(12,'Dia','Este carácter pretende ser el pictograma de un sol. Si recordamos lo que hemos comentado antes acerca de las formas redondeadas, no nos será muy difícil visualizar el círculo y la gran sonrisa que caracteriza a los dibujos más simples que hacemos del sol.','Sol, día y lengua que se agita dentro de la boca.','日',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(13,'Mes','Este carácter es en realidad un dibujo de la luna. Las dos líneas horizontales representan los ojos y la boca de la cara que solemos ver en la superficie de la luna, dibujada por los cráteres del satélite. Los ojos de la luna japonesa son tan alargados que se han unido en una sola línea, y en la línea inferior vemos la boca de esta luna con una generosa sonrisa.','Luna, carne o parte del cuerpo','月',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(14,'Campo de Arroz','Este kanji es otro pictograma con la forma de un campo de arroz dividido en cuatro parcelas y visto desde el aire.','Campo de Arroz y Cerebro','田',1);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(15,'Ojo','Una vez más, si redondeamos los ángulos y curvamos las líneas centrales hacia arriba y hacia abajo respectivamente, obtendremos algo parecido al dibujo de un ojo.','Ojo y Globo Ocular','目',1);

--Leccion 2
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(16,'Viejo','Los componentes que forman este carácter son diez y boca, pero quizás lo encuentres más sencillo de recordar si lo asocias a un pictograma de una tumba con una cruz clavada encima (imagen macabra, sí, pero no por ello menos efectiva). No tienes más que pensar en esas películas de terror en las que a menudo aparecen las viejas tumbas cubiertas de telarañas y marcadas con una cruz. En muy pocos casos ignoraremos los componentes que forman el kanji para utilizar en su lugar un pictograma; esto sólo ocurrirá de vez en cuando en estas primeras fases y prácticamente en ningún caso posteriormente. Así que no te preocupes por tener que aprender demasiados “dibujitos”. ','Como componente, este carácter mantendrá el sentido de la palabra clave, es decir, viejo, pero siempre intentando hacer la noción abstracta tan grá³ca como sea posible. Por eso, vamos a darle el signi³cado de una tumba vieja','古',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(17,'Yo','En realidad, hay varios caracteres que representan la palabra yo, pero los demás kanji suelen tener un signi³cado más especí³co que éste. La palabra clave, en este caso, tendría que interpretarse en el sentido puramente psicológico de “sujeto perceptivo”. El único lugar de nuestros cuerpos en el que se concentran los cinco sentidos con los que percibimos las sensaciones de nuestro alrededor es la cabeza, que tiene ni más ni menos que cinco bocas: dos agujeros de la nariz, dos oídos y una boca. Por tanto, cinco bocas equivale a yo. ','','吾',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(18,'Riesgo','¿Recuerdas que cuando eras niño tu madre siempre insistía en que no miraras nunca directamente al sol porque se te podrían quemar los ojos? Seguramente debías de ser tan alocado como para atreverte a correr el riesgode echar uno o dos vistazos rápidos al sol. Pero por otro lado, también debiste de dar el mismo consejo a alguien más cuando te hiciste mayor. También en este caso, el kanji con un sol en lo alto y un ojo justo debajo que lo observa tiene el sentido de riesgo.','','冒',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(19,'Compañera','Según la historia que cuenta la Biblia, la primera compañera que Dios creó para Adán fue Eva. Al verla, Adán exclamó “¡carnede mi carne!” Y ello es precisamente lo que este carácter expresa a través de sus muchos trazos. Recordemos que el componente, aparte de luna, puede tomar los significados de carne o parte del cuerpo.','','朋',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(20,'Claro','Siguiendo con la Biblia, Dios creó dos brillantes luces y las puso en el cielo para que veamos las cosas claras: el sol para que gobernase el día, y la lunapara que gobernase la noche. Ambas luces representan una de las connotaciones más comunes de esta palabra clave: el sol, la luz clara que ilumina las cosas del día; y la luna, que aclara los misterios de la noche y proporciona inspiración a los poetas.','','明',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(21,'Canto','¡Éste es de lo más fácil! Por una parte tenemos a una boca que no profiere ningún sonido (el director del coro) y dos bocas con sendas lenguas que se agitan en su interior (lo mínimo necesario para formar un coro). Así que solamente hay que pensar en la palabra clave, canto, como un coro monástico, y con ello el kanji será nuestro por los siglos de los siglos.','','唱',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(22,'Destello','¿Qué es lo primero que nos viene a la mente cuando oímos la palabra destello? En la mayoría de los casos la imagen que aparecerá en nuestra mente será la de un diamante. Si colocamos un diamante a la luz del sol cada una de sus facetas brilla como si fuera un sol en miniatura. Este kanji es un dibujo de un pequeño sol triplicado en forma triangular (es decir, “en todas partes”), lo que proporciona el sentido de algo que brilla por todos sus lados: como un diamante. Cuando escribas el componente tres veces, observa cómo la norma de escritura explicada en el cuadro 4 es cierta no solamente aplicada a cada uno de los elementos por separado sino también aplicada al carácter como un todo.','','晶',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(23,'Mercancías','Al igual que pasaba con el carácter de destello, la triplicación de un único elemento en este carácter indica “en todas partes” o “en gran cantidad”. Al pensar en las mercancías de la sociedad moderna, es casi inevitable pensar en algo que ha sido producido en masa, es decir, producido para las “masas” de bocas abiertas que esperan como crías de pájaro en el nido para “consumir” cualquier cosa que se ponga a su alcance.','','品',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(24,'Espina Dorsal','Este carácter es una representación de dos de las vértebras de la espina dorsal unidas por un único trazo.','','呂',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(25,'Próspero','Lo que hemos mencionado en los cuadros 22 y 23, referido a un mismo elemento escrito tres veces para indicar “en todas partes” o “en grandes cantidades” no era algo dicho en broma. En este kanji podemos ver dos soles, uno encima del otro, lo que se puede confundir fácilmente con los tres soles del kanji de destello si no nos andamos con cuidado. Si pensamos en la palabra clave, próspero, podemos relacionarla con el sol fácilmente, ya que solemos referirnos a las épocas prósperas como “días soleados”. ¿Qué hay más próspero, entonces, que un hipotético cielo con dos soles?','','昌',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(26,'Temprano',' Para recordar fácilmente este kanji diremos que es una representación de un girasol que recibe los primeros rayos del sol de la mañana. El girasol no está grá³camente representado en el dibujo pero lo podemos imaginar escondido en alguna parte debajo del kanji, dibujado en tinta invisible. El sol de la mañana aparece temprano y lanza sus rayos cual a³ladas agujas (ver cuadro 10) hacia ese invisible girasol, que recibe esos rayos con los pétalos abiertos.','Como componente, podemos dar a este kanji el signi³cado de girasol, evocando este idílico cuento que hemos inventado.','早',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(27,'Sol Naciente','Podemos asociar este carácter a la bandera japonesa, que exhibe orgullosamente un archiconocido sol naciente. Imaginemos una peculiar bandera japonesa colgada de un bate de béisbol (cuadro 9) y tendremos una curiosa imagen de lo popular que ha llegado a ser el deporte del béisbol en el país del sol naciente.','','旭',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(28,'Generación','Normalmente se considera que una generación corresponde más o menos a un período de treinta (o diez más diez más diez) años. Si observas este kanji en su forma ³nal (sin tener en cuenta el orden de trazos) podrás ver tres veces el número diez. Cuando escribas este kanji piensa que las líneas horizontales de debajo son simples líneas que indican la “suma” de esos tres dieces. Así, la suma de los elementos (diez, diez “más” y diez “más) nos da treinta, es decir, toda una generación. En realidad es mucho más fácil irlo escribiendo con un lápiz que leerlo en un libro.','','世',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(29,'Estómago','Para recordar los significados especiales de los dos componentes que forman este carácter tendrás que volver a los cuadros 13 y 14: se trata de carne (parte del cuerpo) y cerebro. Lo que nos quiere decir este kanji es que la parte del cuerpo que se encarga de mantener en perfecto estado de funcionamiento al cerebro (proporcionándole todo tipo de nutrientes) es el estómago. Para no confundir el orden de los dos elementos al escribir el kanji, intenta pensar en un dibujo estilizado de una persona representado solamente por el cerebro encima y todas las demás partes del cuerpo debajo, sosteniendo al cerebro.','','胃',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(30,'Amanecer','Este kanji nos será fácil de recordar si vemos en él al dibujo de un amanecer, el momento en el que el sol acaba de salir majestuosamente de la línea del horizonte o suelo (ver de nuevo el cuadro 1) para dar paso al día.','','旦',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(31,'Vesícula Biliar','Las dos piezas que forman este carácter son claramente visibles: a la izquierda encontramos el elemento que indica parte del cuerpo y a la derecha el carácter de amanecer que acabamos de ver. Lo único que no está muy claro es la relación de todo esto con la vesícula biliar. Pues bien, la vesícula biliar secreta una sustancia llamada “bilis”, que muy a menudo asociamos en castellano al mal humor. ¿Conoces el proverbio, “No dejes que el sol se ponga sobre tu ira”? Pues bien, tiene su contrario en este kanji, que parece estar diciéndonos: “No dejes que el sol se levante sobre tu ira”. Quien sabe por qué, pero tras una noche de buen sueño nuestro mal humor suele desvanecerse. La vesícula biliar, entonces, se compone de laparte del cuerpo que causa la ira, ira que desaparece al amanecer del día siguiente. Pensar en este kanji nos puede dar un buen consejo: muchas veces es mejor dejar calmar nuestro furor o tantas otras sensaciones humanas poniéndonos a dormir y esperando el amanecer de un nuevo día.','','胆',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(32,'Atravesar','Amanecer, anochecer, amanecer, anochecer.… Los días pasan siguiendo el ritmo del recorrido del sol, que se mueve desde un horizonte (el suelo) hacia el punto álgido al que llega al mediodía (el techo) y a continuación desaparece otra vez tras el horizonte del oeste, día tras día, atravesando el cielo y marcando el curso de nuestros días.','','亘',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(33,'Concavo','¿Qué otra palabra clave iría mejor para este kanji si no es cóncavo? Sólo hay que mirarlo bien: es la viva imagen de una lente cóncava (recuerda que hay que tener presente el fenómeno de cuadriculación que se lleva a cabo en la escritura de los kanji), que cuenta incluso con su pequeño “cráter”. Lo único que falta es aprender a escribirlo.','','凹',2);
INSERT INTO cartas(id,key_word,short_story,as_component,kanji_char,id_leccion) VALUES(34,'Convexo','Gracias a este kanji y al anterior podrás entender perfectamente por qué los japoneses no tienen ningún problema en distinguir los conceptos convexo y cóncavo. Ojo con el tercer trazo, es de lo más extraño. Quizás ahora mismo no te resultará raro, pero cuando hayas terminado de estudiar este libro lo será, ya que los kanji de cóncavo y convexo son de los pocos casos en los que tendrás que trazar esta forma en japonés.','','凸',2);