package com.kardji.main.entidades;
// Generated 25 mar. 2021 18:27:02 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modalidades generated by hbm2java
 */
@Entity
@Table(name = "modalidades")
public class Modalidades implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String description;
	private Set<Utiliza> utilizas = new HashSet<Utiliza>(0);

	public Modalidades() {
	}

	public Modalidades(int id) {
		this.id = id;
	}

	public Modalidades(int id, String name, String description, Set<Utiliza> utilizas) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.utilizas = utilizas;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modalidades")
	public Set<Utiliza> getUtilizas() {
		return this.utilizas;
	}

	public void setUtilizas(Set<Utiliza> utilizas) {
		this.utilizas = utilizas;
	}

}
