package com.kardji.main.entidades;
// Generated 25 mar. 2021 18:27:02 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtilizaId generated by hbm2java
 */
@Embeddable
public class UtilizaId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idLeccion;
	private String fecha;

	public UtilizaId() {
	}

	public UtilizaId(int idLeccion, String fecha) {
		this.idLeccion = idLeccion;
		this.fecha = fecha;
	}

	@Column(name = "idLeccion", nullable = false)
	public int getIdLeccion() {
		return this.idLeccion;
	}

	public void setIdLeccion(int idLeccion) {
		this.idLeccion = idLeccion;
	}

	@Column(name = "fecha", nullable = false)
	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtilizaId))
			return false;
		UtilizaId castOther = (UtilizaId) other;

		return (this.getIdLeccion() == castOther.getIdLeccion())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdLeccion();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
